import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import heroBG from "@/assets/hero-bg.jpg";
import Navbar from "./Utils/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
      title: "Create Next App",
      description: "Generated by create next app",
};

export default function RootLayout({ children }) {
      return (
            <html lang="en">
                  <body className={`${inter.className} bg-background-dark`}>
                        <div className=" sm:w-full max-w-[1440px] mx-auto overflow-hidden">
                              <div className="max-w-[1440px] mx-auto absolute top-0 left-0 right-0 -z-10">
                                    <Image
                                          src={heroBG}
                                          alt="Hero_bg"
                                          width={1920}
                                          height={1080}
                                          className="w-full h-full object-cover "
                                    />
                              </div>
                              <div className="max-w-[1280px] overflow-hidden mx-auto">
                                    <Navbar />
                                    {children}
                              </div>
                        </div>
                  </body>
            </html>
      );
}
